import Header from '@/components/Header/Header'
import NewPages from '@/components/news'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Contacts from '@/components/contact'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header />
       <main className='absolute'>
       {children}
        <NewPages />
        <Contacts />
       </main>
      </body>
    </html>
  )
}
